parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     3306
    database_name:     kit_cms_demo
    database_user:     root
    database_password: 

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       
    mailer_password:   

    locale:             en

    secret:             ThisTokenIsNotSoSecretChangeIt

    kernel.cache_dir:   "/tmp/kit-cms-demo"

    email_contact:      "cms-demo@kitpages.fr"
    email_webmaster:    "cms-demo@kitpages.fr"

    base_url:           http://cmsDemo